FROM rs-grpc-dev:v1.0 AS builder

LABEL authors="daheige"

# 设置环境变量
ENV LANG=C.UTF-8

WORKDIR /app

COPY . .

RUN cd /app && cargo build --release

# 将上面构建好的二进制文件复制到容器中
FROM debian:bullseye-slim

WORKDIR /app

# http gateway端口和metrics端口
EXPOSE 8080
EXPOSE 8091

# 设置deb镜像源，这里我使用aliyun的deb
RUN echo "deb http://mirrors.aliyun.com/debian bullseye main" > /etc/apt/sources.list &&  \
    echo "deb http://mirrors.aliyun.com/debian-security bullseye-security main" >> /etc/apt/sources.list &&  \
    echo "deb http://mirrors.aliyun.com/debian bullseye-updates main" >> /etc/apt/sources.list &&  \
    apt-get update && apt-get install -y ca-certificates vim bash curl net-tools \
    apt-transport-https && update-ca-certificates && apt-get clean &&  \
    rm -rf /var/lib/apt/lists/* && mkdir -p /app/bin

COPY --from=builder /app/target/release/rs-grpc-gateway /app/main
COPY ./bin/entrypoint.sh /app/bin/entrypoint.sh

# 添加执行权限
RUN chmod +x /app/bin/entrypoint.sh

ENTRYPOINT ["/app/bin/entrypoint.sh"]
